FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./

# No lockfile required
RUN npm install --omit=dev

COPY src ./src

FROM node:20-alpine
WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/src ./src
COPY package*.json ./

EXPOSE 8081
CMD ["node", "src/index.js"]
